name: Build Geosite rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set variables
      run: |
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "CHINA_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf" >> $GITHUB_ENV
        echo "GOOGLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf" >> $GITHUB_ENV
        echo "APPLE_DOMAINS_URL=https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf" >> $GITHUB_ENV
        echo "CUSTOM_DIRECT=https://raw.githubusercontent.com/Loyalsoldier/domain-list-custom/release/cn.txt" >> $GITHUB_ENV
      shell: bash

    - name: Get and add direct domains into temp-direct.txt file
      run: |
        curl -sSL $CHINA_DOMAINS_URL | perl -ne '/^server=\/([^\/]+)\// && print "$1\n"' > ./temp-direct.txt
        curl -sSL ${CUSTOM_DIRECT} | perl -ne '/^(domain):([^:]+)(\n$|:@.+)/ && print "$2\n"' >> ./temp-direct.txt

    - name: Move files to publish directory
      run: |
        mkdir -p publish
        mv ./temp-direct.txt ./publish/

    - name: Update GitHub release
      uses: svenstaro/update-release-action@v1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: ./publish/*
        tag: ${{ env.TAG_NAME }}
